// <auto-generated />
using LottoWiki.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LottoWiki.Data.Migrations
{
    [DbContext(typeof(LotofacilContext))]
    [Migration("20241128160721_Name")]
    partial class Name
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LottoWiki.Domain.Models.Entities.LotoFacil", b =>
                {
                    b.Property<int>("Concurso")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ConcursoAnterior")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ProximoConcurso")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("Casa_01")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_02")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_03")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_04")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_05")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_06")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_07")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_08")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_09")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_10")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_11")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_12")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_13")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_14")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_15")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("DataApuracao")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("LuaDoSorteio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("NomeMunicipioUFSorteio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Concurso", "ConcursoAnterior", "ProximoConcurso");

                    b.ToTable("base.lotoFacil", (string)null);

                    b.HasData(
                        new
                        {
                            Concurso = 1,
                            ConcursoAnterior = 0,
                            ProximoConcurso = 2,
                            Casa_01 = 18,
                            Casa_02 = 20,
                            Casa_03 = 25,
                            Casa_04 = 23,
                            Casa_05 = 10,
                            Casa_06 = 11,
                            Casa_07 = 24,
                            Casa_08 = 14,
                            Casa_09 = 6,
                            Casa_10 = 2,
                            Casa_11 = 13,
                            Casa_12 = 9,
                            Casa_13 = 5,
                            Casa_14 = 16,
                            Casa_15 = 3,
                            DataApuracao = "01/02/1989",
                            LuaDoSorteio = "Crescente",
                            NomeMunicipioUFSorteio = "CRUZ ALTA, RS"
                        },
                        new
                        {
                            Concurso = 2,
                            ConcursoAnterior = 1,
                            ProximoConcurso = 3,
                            Casa_01 = 23,
                            Casa_02 = 15,
                            Casa_03 = 5,
                            Casa_04 = 4,
                            Casa_05 = 12,
                            Casa_06 = 16,
                            Casa_07 = 20,
                            Casa_08 = 6,
                            Casa_09 = 11,
                            Casa_10 = 19,
                            Casa_11 = 24,
                            Casa_12 = 1,
                            Casa_13 = 9,
                            Casa_14 = 13,
                            Casa_15 = 7,
                            DataApuracao = "02/02/1989",
                            LuaDoSorteio = "Crescente",
                            NomeMunicipioUFSorteio = "CRUZ ALTA, RS"
                        },
                        new
                        {
                            Concurso = 3,
                            ConcursoAnterior = 2,
                            ProximoConcurso = 4,
                            Casa_01 = 20,
                            Casa_02 = 23,
                            Casa_03 = 12,
                            Casa_04 = 8,
                            Casa_05 = 6,
                            Casa_06 = 1,
                            Casa_07 = 7,
                            Casa_08 = 11,
                            Casa_09 = 14,
                            Casa_10 = 4,
                            Casa_11 = 16,
                            Casa_12 = 10,
                            Casa_13 = 9,
                            Casa_14 = 17,
                            Casa_15 = 24,
                            DataApuracao = "02/02/1989",
                            LuaDoSorteio = "Crescente",
                            NomeMunicipioUFSorteio = "CRUZ ALTA, RS"
                        });
                });

            modelBuilder.Entity("LottoWiki.Domain.Models.Entities.LotoFacilDoOver", b =>
                {
                    b.Property<int>("Concurso")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ConcursoAnterior")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ProximoConcurso")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("Bola_01")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_02")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_03")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_04")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_05")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_06")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_07")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_08")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_09")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_10")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_11")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_12")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_13")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_14")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_15")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_16")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_17")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_18")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_19")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_20")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_21")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_22")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_23")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_24")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_25")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("Concurso", "ConcursoAnterior", "ProximoConcurso");

                    b.ToTable("bola.repetida", (string)null);

                    b.HasData(
                        new
                        {
                            Concurso = 1,
                            ConcursoAnterior = 0,
                            ProximoConcurso = 2,
                            Bola_01 = 1,
                            Bola_02 = 0,
                            Bola_03 = 1,
                            Bola_04 = 1,
                            Bola_05 = 0,
                            Bola_06 = 0,
                            Bola_07 = 1,
                            Bola_08 = 1,
                            Bola_09 = 0,
                            Bola_10 = 0,
                            Bola_11 = 0,
                            Bola_12 = 1,
                            Bola_13 = 0,
                            Bola_14 = 0,
                            Bola_15 = 1,
                            Bola_16 = 0,
                            Bola_17 = 0,
                            Bola_18 = 1,
                            Bola_19 = 1,
                            Bola_20 = 0,
                            Bola_21 = 1,
                            Bola_22 = 1,
                            Bola_23 = 0,
                            Bola_24 = 0,
                            Bola_25 = 0
                        },
                        new
                        {
                            Concurso = 2,
                            ConcursoAnterior = 1,
                            ProximoConcurso = 3,
                            Bola_01 = 2,
                            Bola_02 = 1,
                            Bola_03 = 1,
                            Bola_04 = 0,
                            Bola_05 = 0,
                            Bola_06 = 0,
                            Bola_07 = 0,
                            Bola_08 = 1,
                            Bola_09 = 0,
                            Bola_10 = 1,
                            Bola_11 = 0,
                            Bola_12 = 0,
                            Bola_13 = 0,
                            Bola_14 = 1,
                            Bola_15 = 0,
                            Bola_16 = 0,
                            Bola_17 = 1,
                            Bola_18 = 1,
                            Bola_19 = 0,
                            Bola_20 = 0,
                            Bola_21 = 2,
                            Bola_22 = 2,
                            Bola_23 = 0,
                            Bola_24 = 0,
                            Bola_25 = 1
                        },
                        new
                        {
                            Concurso = 3,
                            ConcursoAnterior = 2,
                            ProximoConcurso = 4,
                            Bola_01 = 0,
                            Bola_02 = 2,
                            Bola_03 = 2,
                            Bola_04 = 0,
                            Bola_05 = 1,
                            Bola_06 = 0,
                            Bola_07 = 0,
                            Bola_08 = 0,
                            Bola_09 = 0,
                            Bola_10 = 0,
                            Bola_11 = 0,
                            Bola_12 = 0,
                            Bola_13 = 1,
                            Bola_14 = 0,
                            Bola_15 = 1,
                            Bola_16 = 0,
                            Bola_17 = 0,
                            Bola_18 = 2,
                            Bola_19 = 1,
                            Bola_20 = 0,
                            Bola_21 = 3,
                            Bola_22 = 3,
                            Bola_23 = 0,
                            Bola_24 = 0,
                            Bola_25 = 2
                        });
                });

            modelBuilder.Entity("LottoWiki.Domain.Models.Entities.LotoFacilOverdue", b =>
                {
                    b.Property<int>("Concurso")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ConcursoAnterior")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ProximoConcurso")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("Bola_01")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_02")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_03")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_04")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_05")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_06")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_07")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_08")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_09")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_10")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_11")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_12")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_13")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_14")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_15")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_16")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_17")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_18")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_19")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_20")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_21")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_22")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_23")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_24")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Bola_25")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("Concurso", "ConcursoAnterior", "ProximoConcurso");

                    b.ToTable("bola.atraso", (string)null);

                    b.HasData(
                        new
                        {
                            Concurso = 1,
                            ConcursoAnterior = 0,
                            ProximoConcurso = 2,
                            Bola_01 = 1,
                            Bola_02 = 0,
                            Bola_03 = 1,
                            Bola_04 = 1,
                            Bola_05 = 0,
                            Bola_06 = 0,
                            Bola_07 = 1,
                            Bola_08 = 1,
                            Bola_09 = 0,
                            Bola_10 = 0,
                            Bola_11 = 0,
                            Bola_12 = 1,
                            Bola_13 = 0,
                            Bola_14 = 0,
                            Bola_15 = 1,
                            Bola_16 = 0,
                            Bola_17 = 0,
                            Bola_18 = 1,
                            Bola_19 = 1,
                            Bola_20 = 0,
                            Bola_21 = 1,
                            Bola_22 = 1,
                            Bola_23 = 0,
                            Bola_24 = 0,
                            Bola_25 = 0
                        },
                        new
                        {
                            Concurso = 2,
                            ConcursoAnterior = 1,
                            ProximoConcurso = 3,
                            Bola_01 = 2,
                            Bola_02 = 1,
                            Bola_03 = 1,
                            Bola_04 = 0,
                            Bola_05 = 0,
                            Bola_06 = 0,
                            Bola_07 = 0,
                            Bola_08 = 1,
                            Bola_09 = 0,
                            Bola_10 = 1,
                            Bola_11 = 0,
                            Bola_12 = 0,
                            Bola_13 = 0,
                            Bola_14 = 1,
                            Bola_15 = 0,
                            Bola_16 = 0,
                            Bola_17 = 1,
                            Bola_18 = 1,
                            Bola_19 = 0,
                            Bola_20 = 0,
                            Bola_21 = 2,
                            Bola_22 = 2,
                            Bola_23 = 0,
                            Bola_24 = 0,
                            Bola_25 = 1
                        },
                        new
                        {
                            Concurso = 3,
                            ConcursoAnterior = 2,
                            ProximoConcurso = 4,
                            Bola_01 = 0,
                            Bola_02 = 2,
                            Bola_03 = 2,
                            Bola_04 = 0,
                            Bola_05 = 1,
                            Bola_06 = 0,
                            Bola_07 = 0,
                            Bola_08 = 0,
                            Bola_09 = 0,
                            Bola_10 = 0,
                            Bola_11 = 0,
                            Bola_12 = 0,
                            Bola_13 = 1,
                            Bola_14 = 0,
                            Bola_15 = 1,
                            Bola_16 = 0,
                            Bola_17 = 0,
                            Bola_18 = 2,
                            Bola_19 = 1,
                            Bola_20 = 0,
                            Bola_21 = 3,
                            Bola_22 = 3,
                            Bola_23 = 0,
                            Bola_24 = 0,
                            Bola_25 = 2
                        });
                });

            modelBuilder.Entity("LottoWiki.Domain.Models.Entities.LotoFacilStatus", b =>
                {
                    b.Property<int>("Concurso")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ConcursoAnterior")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ProximoConcurso")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Bola_01")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_02")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_03")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_04")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_05")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_06")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_07")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_08")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_09")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_10")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_11")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_12")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_13")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_14")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_15")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_16")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_17")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_18")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_19")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_20")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_21")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_22")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_23")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_24")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("Bola_25")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.HasKey("Concurso", "ConcursoAnterior", "ProximoConcurso");

                    b.ToTable("bola.status", (string)null);

                    b.HasData(
                        new
                        {
                            Concurso = 1,
                            ConcursoAnterior = 0,
                            ProximoConcurso = 2,
                            Bola_01 = "A",
                            Bola_02 = "N",
                            Bola_03 = "N",
                            Bola_04 = "A",
                            Bola_05 = "N",
                            Bola_06 = "N",
                            Bola_07 = "A",
                            Bola_08 = "A",
                            Bola_09 = "N",
                            Bola_10 = "N",
                            Bola_11 = "N",
                            Bola_12 = "A",
                            Bola_13 = "N",
                            Bola_14 = "N",
                            Bola_15 = "A",
                            Bola_16 = "N",
                            Bola_17 = "A",
                            Bola_18 = "N",
                            Bola_19 = "A",
                            Bola_20 = "N",
                            Bola_21 = "A",
                            Bola_22 = "A",
                            Bola_23 = "N",
                            Bola_24 = "N",
                            Bola_25 = "N"
                        },
                        new
                        {
                            Concurso = 2,
                            ConcursoAnterior = 1,
                            ProximoConcurso = 3,
                            Bola_01 = "R",
                            Bola_02 = "R",
                            Bola_03 = "R",
                            Bola_04 = "R",
                            Bola_05 = "R",
                            Bola_06 = "R",
                            Bola_07 = "R",
                            Bola_08 = "R",
                            Bola_09 = "R",
                            Bola_10 = "R",
                            Bola_11 = "R",
                            Bola_12 = "R",
                            Bola_13 = "R",
                            Bola_14 = "R",
                            Bola_15 = "R",
                            Bola_16 = "R",
                            Bola_17 = "R",
                            Bola_18 = "R",
                            Bola_19 = "R",
                            Bola_20 = "R",
                            Bola_21 = "R",
                            Bola_22 = "R",
                            Bola_23 = "R",
                            Bola_24 = "R",
                            Bola_25 = "R"
                        },
                        new
                        {
                            Concurso = 3,
                            ConcursoAnterior = 2,
                            ProximoConcurso = 4,
                            Bola_01 = "A",
                            Bola_02 = "A",
                            Bola_03 = "A",
                            Bola_04 = "A",
                            Bola_05 = "A",
                            Bola_06 = "A",
                            Bola_07 = "A",
                            Bola_08 = "A",
                            Bola_09 = "A",
                            Bola_10 = "A",
                            Bola_11 = "A",
                            Bola_12 = "A",
                            Bola_13 = "A",
                            Bola_14 = "A",
                            Bola_15 = "A",
                            Bola_16 = "A",
                            Bola_17 = "A",
                            Bola_18 = "A",
                            Bola_19 = "A",
                            Bola_20 = "A",
                            Bola_21 = "A",
                            Bola_22 = "A",
                            Bola_23 = "A",
                            Bola_24 = "A",
                            Bola_25 = "A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
